//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMonitoring.BusinessLogin.SensorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IModelDto", Namespace="http://schemas.datacontract.org/2004/07/SensorMonitoring.Data.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.UserDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto))]
    public partial class IModelDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/SensorMonitoring.Data.Models")]
    [System.SerializableAttribute()]
    public partial class UserDto : SensorMonitoring.BusinessLogin.SensorServiceReference.IModelDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SensorDto", Namespace="http://schemas.datacontract.org/2004/07/SensorMonitoring.Data.Models")]
    [System.SerializableAttribute()]
    public partial class SensorDto : SensorMonitoring.BusinessLogin.SensorServiceReference.IModelDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SensorMonitoring.BusinessLogin.SensorServiceReference.UserDto MasterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubstanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension {
            get {
                return this.DimensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionField, value) != true)) {
                    this.DimensionField = value;
                    this.RaisePropertyChanged("Dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SensorMonitoring.BusinessLogin.SensorServiceReference.UserDto Master {
            get {
                return this.MasterField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterField, value) != true)) {
                    this.MasterField = value;
                    this.RaisePropertyChanged("Master");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Substance {
            get {
                return this.SubstanceField;
            }
            set {
                if ((object.ReferenceEquals(this.SubstanceField, value) != true)) {
                    this.SubstanceField = value;
                    this.RaisePropertyChanged("Substance");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SensorServiceReference.IDataServiceOf_SensorDto")]
    public interface IDataServiceOf_SensorDto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.IModelDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.UserDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto[]))]
        SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto GetItem(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetItemResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto> GetItemAsync(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetResponse")]
        SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItemResponse")]
        void UpdateItem(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/AddItemResponse")]
        void AddItem(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceOf_SensorDtoChannel : SensorMonitoring.BusinessLogin.SensorServiceReference.IDataServiceOf_SensorDto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceOf_SensorDtoClient : System.ServiceModel.ClientBase<SensorMonitoring.BusinessLogin.SensorServiceReference.IDataServiceOf_SensorDto>, SensorMonitoring.BusinessLogin.SensorServiceReference.IDataServiceOf_SensorDto {
        
        public DataServiceOf_SensorDtoClient() {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_SensorDtoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto GetItem(object[] keys) {
            return base.Channel.GetItem(keys);
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto> GetItemAsync(object[] keys) {
            return base.Channel.GetItemAsync(keys);
        }
        
        public SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public void UpdateItem(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item) {
            base.Channel.UpdateItem(item);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item) {
            return base.Channel.UpdateItemAsync(item);
        }
        
        public void AddItem(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item) {
            base.Channel.AddItem(item);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.BusinessLogin.SensorServiceReference.SensorDto item) {
            return base.Channel.AddItemAsync(item);
        }
    }
}
