//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMonitoring.BusinessLogin.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IDataServiceOf_UserDto")]
    public interface IDataServiceOf_UserDto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/GetItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.UserDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.IModelDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.UserDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        SensorMonitoring.Data.DTO.UserDto GetItem(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/GetItemResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.UserDto> GetItemAsync(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/GetResponse")]
        SensorMonitoring.Data.DTO.UserDto[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/GetResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.UserDto[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/UpdateItemResponse")]
        void UpdateItem(SensorMonitoring.Data.DTO.UserDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.Data.DTO.UserDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/AddItemResponse")]
        void AddItem(SensorMonitoring.Data.DTO.UserDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_UserDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_UserDto/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.Data.DTO.UserDto item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceOf_UserDtoChannel : SensorMonitoring.BusinessLogin.UserServiceReference.IDataServiceOf_UserDto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceOf_UserDtoClient : System.ServiceModel.ClientBase<SensorMonitoring.BusinessLogin.UserServiceReference.IDataServiceOf_UserDto>, SensorMonitoring.BusinessLogin.UserServiceReference.IDataServiceOf_UserDto {
        
        public DataServiceOf_UserDtoClient() {
        }
        
        public DataServiceOf_UserDtoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceOf_UserDtoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_UserDtoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_UserDtoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SensorMonitoring.Data.DTO.UserDto GetItem(object[] keys) {
            return base.Channel.GetItem(keys);
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.UserDto> GetItemAsync(object[] keys) {
            return base.Channel.GetItemAsync(keys);
        }
        
        public SensorMonitoring.Data.DTO.UserDto[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.UserDto[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public void UpdateItem(SensorMonitoring.Data.DTO.UserDto item) {
            base.Channel.UpdateItem(item);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.Data.DTO.UserDto item) {
            return base.Channel.UpdateItemAsync(item);
        }
        
        public void AddItem(SensorMonitoring.Data.DTO.UserDto item) {
            base.Channel.AddItem(item);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.Data.DTO.UserDto item) {
            return base.Channel.AddItemAsync(item);
        }
    }
}
