//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMonitoring.BusinessLogin.SensorServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SensorServiceReference1.IDataServiceOf_SensorDto")]
    public interface IDataServiceOf_SensorDto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.SensorDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.IModelDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SensorMonitoring.Data.DTO.SensorDto[]))]
        SensorMonitoring.Data.DTO.SensorDto GetItem(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/GetItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetItemResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.SensorDto> GetItemAsync(object[] keys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetResponse")]
        SensorMonitoring.Data.DTO.SensorDto[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/Get", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/GetResponse")]
        System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.SensorDto[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItemResponse")]
        void UpdateItem(SensorMonitoring.Data.DTO.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.Data.DTO.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/AddItemResponse")]
        void AddItem(SensorMonitoring.Data.DTO.SensorDto item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataServiceOf_SensorDto/AddItem", ReplyAction="http://tempuri.org/IDataServiceOf_SensorDto/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.Data.DTO.SensorDto item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceOf_SensorDtoChannel : SensorMonitoring.BusinessLogin.SensorServiceReference1.IDataServiceOf_SensorDto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceOf_SensorDtoClient : System.ServiceModel.ClientBase<SensorMonitoring.BusinessLogin.SensorServiceReference1.IDataServiceOf_SensorDto>, SensorMonitoring.BusinessLogin.SensorServiceReference1.IDataServiceOf_SensorDto {
        
        public DataServiceOf_SensorDtoClient() {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_SensorDtoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceOf_SensorDtoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SensorMonitoring.Data.DTO.SensorDto GetItem(object[] keys) {
            return base.Channel.GetItem(keys);
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.SensorDto> GetItemAsync(object[] keys) {
            return base.Channel.GetItemAsync(keys);
        }
        
        public SensorMonitoring.Data.DTO.SensorDto[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<SensorMonitoring.Data.DTO.SensorDto[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public void UpdateItem(SensorMonitoring.Data.DTO.SensorDto item) {
            base.Channel.UpdateItem(item);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(SensorMonitoring.Data.DTO.SensorDto item) {
            return base.Channel.UpdateItemAsync(item);
        }
        
        public void AddItem(SensorMonitoring.Data.DTO.SensorDto item) {
            base.Channel.AddItem(item);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(SensorMonitoring.Data.DTO.SensorDto item) {
            return base.Channel.AddItemAsync(item);
        }
    }
}
